services:

  postgres:
    image: postgres:17.2
    restart: always
    ports:
      - 5432:5432
    networks:
      - mynet
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./sql/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 80:80
    networks:
      - mynet
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@test.ro
      - PGADMIN_DEFAULT_PASSWORD=postgres

  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - mynet
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    networks:
      - mynet
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  mynet:
    driver: bridge
