services:

  postgres:
    container_name: dcpm_pgsql
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dcpm
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dcpm-net
    restart: unless-stopped

  pgadmin:
    container_name: dcpm_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@test.ro}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    ports:
      - 5050:80
    networks:
      - dcpm-net
    restart: unless-stopped

  zookeeper:
    container_name: dcpm_zookeeper
    image: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181
    networks:
      - dcpm-net
    restart: unless-stopped

networks:
  dcpm-net:
    driver: bridge

volumes:
  postgres: