server:
  port: 8082
spring:
  application:
    name: inventory
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/dcpm
    username: postgres
    password: postgres
  liquibase:
    default-schema: inventory
  cloud:
    zookeeper:
      connect-string: localhost:2181
logging:
  level:
    ro.dma.dcpm: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace